export const mockUsers = [
    {
      id: 1,
      name: "László Nagy",
      profilePicture: "https://randomuser.me/api/portraits/men/1.jpg",
      statusMessage: "Enjoying the sunshine! ☀️",
      friends: [2, 3],
    },
    {
      id: 2,
      name: "Judit Kovács",
      profilePicture: "https://randomuser.me/api/portraits/women/1.jpg",
      statusMessage: "Reading a great book. 📚",
      friends: [1],
    },
    {
      id: 3,
      name: "Tamás Szabó",
      profilePicture: "https://randomuser.me/api/portraits/men/2.jpg",
      statusMessage: "Excited for the weekend! 🎉",
      friends: [1],
    },
    {
      id: 4,
      name: "Erika Tóth",
      profilePicture: "https://randomuser.me/api/portraits/women/2.jpg",
      statusMessage: "Just got a new puppy! 🐶",
      friends: [5, 6],
    },
    {
      id: 5,
      name: "Zoltán Varga",
      profilePicture: "https://randomuser.me/api/portraits/men/3.jpg",
      statusMessage: "Running a marathon next week. 🏃‍♂️",
      friends: [4, 6],
    },
    {
      id: 6,
      name: "Anna Horváth",
      profilePicture: "https://randomuser.me/api/portraits/women/3.jpg",
      statusMessage: "Learning to cook something new. 🍳",
      friends: [4, 5],
    },
    {
      id: 7,
      name: "Gábor Kis",
      profilePicture: "https://randomuser.me/api/portraits/men/4.jpg",
      statusMessage: "Planning my next vacation. ✈️",
      friends: [8, 9],
    },
    {
      id: 8,
      name: "Eszter Molnár",
      profilePicture: "https://randomuser.me/api/portraits/women/4.jpg",
      statusMessage: "Enjoying a quiet weekend.",
      friends: [7, 9],
    },
    {
      id: 9,
      name: "Bence Farkas",
      profilePicture: "https://randomuser.me/api/portraits/men/5.jpg",
      statusMessage: "Working on a new project. 💻",
      friends: [7, 8],
    },
    {
      id: 10,
      name: "Mária Papp",
      profilePicture: "https://randomuser.me/api/portraits/women/5.jpg",
      statusMessage: "Starting a new job today!",
      friends: [11, 12],
    },
    {
      id: 11,
      name: "Lajos Balogh",
      profilePicture: "https://randomuser.me/api/portraits/men/6.jpg",
      statusMessage: "Trying out yoga for the first time. 🧘‍♂️",
      friends: [10, 12],
    },
    {
      id: 12,
      name: "Rita Kocsis",
      profilePicture: "https://randomuser.me/api/portraits/women/6.jpg",
      statusMessage: "Binge-watching a new series. 🍿",
      friends: [10, 11],
    },
    {
      id: 13,
      name: "Péter Sándor",
      profilePicture: "https://randomuser.me/api/portraits/men/7.jpg",
      statusMessage: "Enjoying a cup of coffee. ☕",
      friends: [14, 15],
    },
    {
      id: 14,
      name: "József Kiss",
      profilePicture: "https://randomuser.me/api/portraits/men/8.jpg",
      statusMessage: "Going hiking this weekend. 🥾",
      friends: [13, 15],
    },
    {
      id: 15,
      name: "Zsuzsanna Takács",
      profilePicture: "https://randomuser.me/api/portraits/women/7.jpg",
      statusMessage: "Reading a mystery novel. 🔍",
      friends: [13, 14],
    },
    {
      id: 16,
      name: "Imre Szalai",
      profilePicture: "https://randomuser.me/api/portraits/men/9.jpg",
      statusMessage: "Playing some guitar. 🎸",
      friends: [17, 18],
    },
    {
      id: 17,
      name: "Ildikó Németh",
      profilePicture: "https://randomuser.me/api/portraits/women/8.jpg",
      statusMessage: "Baking cookies. 🍪",
      friends: [16, 18],
    },
    {
      id: 18,
      name: "Zoltán Lakatos",
      profilePicture: "https://randomuser.me/api/portraits/men/10.jpg",
      statusMessage: "Running some errands.",
      friends: [16, 17],
    },
    {
      id: 19,
      name: "Éva Juhász",
      profilePicture: "https://randomuser.me/api/portraits/women/9.jpg",
      statusMessage: "Playing with my cat. 🐱",
      friends: [20, 21],
    },
    {
      id: 20,
      name: "Csaba Pál",
      profilePicture: "https://randomuser.me/api/portraits/men/11.jpg",
      statusMessage: "Catching up on sleep. 😴",
      friends: [19, 21],
    },
    {
      id: 21,
      name: "Tímea Simon",
      profilePicture: "https://randomuser.me/api/portraits/women/10.jpg",
      statusMessage: "Exploring a new city. 🏙️",
      friends: [19, 20],
    },
    {
      id: 22,
      name: "György Kocsis",
      profilePicture: "https://randomuser.me/api/portraits/men/12.jpg",
      statusMessage: "Working on my blog.",
      friends: [23, 24],
    },
    {
      id: 23,
      name: "Ágnes Szűcs",
      profilePicture: "https://randomuser.me/api/portraits/women/11.jpg",
      statusMessage: "Starting a new hobby. 🎨",
      friends: [22, 24],
    },
    {
      id: 24,
      name: "Ferenc Pásztor",
      profilePicture: "https://randomuser.me/api/portraits/men/13.jpg",
      statusMessage: "Visiting family. 👨‍👩‍👧‍👦",
      friends: [22, 23],
    },
    {
      id: 25,
      name: "Katalin Fodor",
      profilePicture: "https://randomuser.me/api/portraits/women/12.jpg",
      statusMessage: "Learning a new language. 🌍",
      friends: [26, 27],
    },
    {
        id: 26,
        name: "Jana Kolos",
        profilePicture: 'https://randomuser.me/api/portraits/women/44.jpg', // RandomUser API image
        statusMessage: "Learning a new language. 🌍",
        friends: [1,2,3,4,5,6,7,8,9,10,11,12, 13, 14, 15,],
      }
  ];
  